const PUBLIC_BAIDU_TRANSPORT_SERVER_CODES = Object.freeze([
  'BAIDU_HTTP_ERROR',
  'BAIDU_REQUEST_TIMEOUT',
  'BAIDU_RESPONSE_INVALID',
  'BAIDU_RESPONSE_TOO_LARGE',
  'BAIDU_UPSTREAM_UNAVAILABLE'
]);

const PUBLIC_MARKETING_SERVER_CODES = Object.freeze({
  dashboard: Object.freeze([
    ...PUBLIC_BAIDU_TRANSPORT_SERVER_CODES,
    'BAIDU_REPORT_FAILED',
    'MARKETING_MODULE_UNAVAILABLE'
  ]),
  tongji: Object.freeze([
    ...PUBLIC_BAIDU_TRANSPORT_SERVER_CODES,
    'BAIDU_TONGJI_CAPABILITY_NOT_VERIFIED',
    'BAIDU_TONGJI_FAILED',
    'BAIDU_TONGJI_PAGE_REPORT_BUDGET_EXCEEDED',
    'BAIDU_TONGJI_RESPONSE_INVALID',
    'TONGJI_CACHE_INVALID',
    'TONGJI_PAGE_PROVIDER_MISSING',
    'TONGJI_PAGE_RESPONSE_INVALID',
    'TONGJI_QUALITY_RESPONSE_INVALID',
    'TONGJI_RESPONSE_INVALID',
    'TONGJI_SITE_MISMATCH',
    'TONGJI_SOURCE_PARTITION_INVALID',
    'TONGJI_SOURCE_RESPONSE_INVALID',
    'TONGJI_SOURCE_TREND_MISMATCH',
    'TONGJI_UPSTREAM_FAILED'
  ]),
  refresh: Object.freeze([
    'MARKETING_EXECUTOR_QUEUE_FULL',
    'MARKETING_EXECUTOR_NOT_ACCEPTING'
  ])
});

module.exports = {
  PUBLIC_BAIDU_TRANSPORT_SERVER_CODES,
  PUBLIC_MARKETING_SERVER_CODES
};
